name: Trigger auto deployment for demo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/demo-AutoDeployTrigger-19627ebc-83a6-4a0a-a94c-bc019808da3a.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca38371f0776acr.azurecr.io
          username: ${{ secrets.DEMO_REGISTRY_USERNAME }}
          password: ${{ secrets.DEMO_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca38371f0776acr.azurecr.io/demo:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEMO_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n demo -g container_apps --server ca38371f0776acr.azurecr.io --username  ${{ secrets.DEMO_REGISTRY_USERNAME }} --password ${{ secrets.DEMO_REGISTRY_PASSWORD }}
            az containerapp update -n demo -g container_apps --image ca38371f0776acr.azurecr.io/demo:${{ github.sha }}
