name: Trigger auto deployment for ghtest1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ghtest1-AutoDeployTrigger-22fd7020-4143-4134-9b4c-59ab271726fe.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca8a296b2511acr.azurecr.io
          username: ${{ secrets.GHTEST1_REGISTRY_USERNAME }}
          password: ${{ secrets.GHTEST1_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca8a296b2511acr.azurecr.io/ghtest1:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GHTEST1_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ghtest1 -g container_apps --server ca8a296b2511acr.azurecr.io --username  ${{ secrets.GHTEST1_REGISTRY_USERNAME }} --password ${{ secrets.GHTEST1_REGISTRY_PASSWORD }}
            az containerapp update -n ghtest1 -g container_apps --image ca8a296b2511acr.azurecr.io/ghtest1:${{ github.sha }}
